### ISSUE TITLE
Still supported

### ISSUE THREAD

**Issue by 1602** [yads/jugglingdb-azure-tablestorage#1]
Any plans on continuing support of this adapter?

**Comment by yads** [comment]
What kind of additional functionality is needed atm?

**Comment by 1602** [comment]
I plan to make some significant changes in jugglingdb core and wanted to make sure actual adapters will survive.

At least only one thing needed so far: tests; just ensure all current tests for jugglindb@2.0.0-rc5 pass. I'm more than happy to help with testing if you help with db setup, ideally using docker image.

100% coverage and latest dependencies + latest node won't hurt as well.

**Comment by yads** [comment]
So there are currently tests, but they are meant to go against jugglingdb v1. I can update the deps as well.
